export const date = [
    {
        title: 'Apple iPhone 11',
        quantity: 12,
        yearOfRelease: 2018,
        producer: 'Apple',
        color: 'белый',
        numberOfCameras: 3,
        isPopular: true,
        img: 'https://rs-online-store.netlify.app/assets/toys/7.png',
    },
    {
        title: 'Samsung Galaxy S20',
        quantity: 3,
        yearOfRelease: 2022,
        producer: 'Samsung',
        color: 'желтый',
        numberOfCameras: 1,
        isPopular: false,
        img: 'https://rs-online-store.netlify.app/assets/toys/3.png',
    },
    {
        title: 'Apple iPhone 13',
        quantity: 10,
        yearOfRelease: 2009,
        producer: 'Apple',
        color: 'красный',
        numberOfCameras: 3,
        isPopular: false,
        img: 'https://rs-online-store.netlify.app/assets/toys/8.png',
    },
    {
        title: 'Xiaomi Poco X4 pro',
        quantity: 1,
        yearOfRelease: 2014,
        producer: 'Xiaomi',
        color: 'желтый',
        numberOfCameras: 2,
        isPopular: false,
        img: 'https://rs-online-store.netlify.app/assets/toys/4.png',
    },
    {
        title: 'Apple iPhone SE',
        quantity: 7,
        yearOfRelease: 2004,
        producer: 'Apple',
        color: 'белый',
        numberOfCameras: 1,
        isPopular: false,
        img: 'https://rs-online-store.netlify.app/assets/toys/10.png',
    },
    {
        title: 'Samsung Galaxy A03',
        quantity: 5,
        yearOfRelease: 2000,
        producer: 'Samsung',
        color: 'красный',
        numberOfCameras: 2,
        isPopular: false,
        img: 'https://rs-online-store.netlify.app/assets/toys/2.png',
    },
    {
        title: 'Xiaomi Redmi Note 11',
        quantity: 4,
        yearOfRelease: 2012,
        producer: 'Xiaomi',
        color: 'белый',
        numberOfCameras: 1,
        isPopular: true,
        img: 'https://rs-online-store.netlify.app/assets/toys/5.png',
    },
    {
        title: 'Apple iPhone 12',
        quantity: 2,
        yearOfRelease: 2010,
        producer: 'Apple',
        color: 'желтый',
        numberOfCameras: 3,
        isPopular: false,
        img: 'https://rs-online-store.netlify.app/assets/toys/9.png',
    },
    {
        title: 'Samsung Galaxy S21',
        quantity: 2,
        yearOfRelease: 2019,
        producer: 'Samsung',
        color: 'белый',
        numberOfCameras: 3,
        isPopular: false,
        img: 'https://rs-online-store.netlify.app/assets/toys/1.png',
    },
    {
        title: 'Xiaomi Redmi 9C 3/64gb',
        quantity: 6,
        yearOfRelease: 2010,
        producer: 'Xiaomi',
        color: 'красный',
        numberOfCameras: 2,
        isPopular: false,
        img: 'https://rs-online-store.netlify.app/assets/toys/6.png',
    },
];